name: proyecto_prodegua
description: App híbrida para gestión de servicios de Prodegua

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  fl_chart: ^0.66.0
  sqflite_common_ffi: ^2.3.1
  path: ^1.9.0

  shared_preferences: ^2.2.2

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
